### PR TITLE
JOSS Review: Seaborn and notebooks 

### LINKED ISSUE #8: Exceptions in example notebooks
I just tried running the following notebooks from the `scripts` folder: 'MSWH System Tool.ipynb', 'MSWH System Tool - Playground.ipynb', and 'MSWH System Tool - for CEC Report.ipynb' and couldn't get them to run in their entirety, namely:

1. they depend on seaborn, which isn't in the mswh requirements
2. they raise an exception in the `Individual retrofit solar thermal system` section (~cell 55): ``ERROR:mswh.system.models:Check project output of the backup - timestep sum preformed in this method and the total are not equal.``
3. There's also another exception in  'MSWH System Tool - Playground.ipynb', cell 38: ``NameError: name 'cold_cz' is not defined``

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)

### PR DESCRIPTION
**Pull request by milicag**
This closes #8.

I added `seaborn` dependency to setup.py, and added a couple items to `.gitignore` for more convenient usage. I also deleted an obsolete notebooks. All notebooks run fine on my machine.

I fixed the missing `cold_cz` string (changed to the playground location climate zone). This was a copy/paste omission.

@brynpickering Please note that I was not able to reproduce this error you were getting:
```
they raise an exception in the Individual retrofit solar thermal system section (~cell 55): ERROR:mswh.system.models:Check project output of the backup - timestep sum preformed in this method and the total are not equal.
```
neither in the `MSWH System Tool.ipynb` - first screenshot below, nor in the playground version - second screenshot below. Please take a look at screenshots attached and let me know if the error was occurring in a different spot in the notebook code.

Capture

Capture_playground

### CODE REVIEW

**Comment by milicag** [comment]
@brynpickering please test at your convenience. I appreciate your review.

If you still get the error, it would be useful if you could please share the versions of the dependencies that you have in the `jupyter` kernel that runs the notebook.

**Comment by milicag** [comment]
Also please note that I did not have `seaborn` in the dependencies on purpose, as it is not a dependency of the python package - it is just used in the notebooks. Is this the general practice of the Journal to include the notebook dependencies? I can see pros and cons to that approach.

**Comment by brynpickering** [comment]
Thanks for updating the gitignore.
I agree that it's a bit strange having seaborn as a dependency, given that it's not a requirement of the core code. The easiest is probably to remove it entirely from the notebook, it doesn't add anything since all your plotting is through your internal function `Plot`. In fact, you also don't need to load plotly or 'initialise' the notebook. Removing the lines:

```python
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
import seaborn as sns
sns.set(rc={'figure.figsize':(16,12)})
sns.set_style("whitegrid")
```
I get the same result on the first plot (right: before removal, left: after removal):
Screenshot 2020-10-15 at 14 57 28

It's probably worth checking and removing all redundant packages from the initialisation of the notebook. This will ensure that they're easier to maintain in future.

**Comment by milicag** [comment]
Thanks @brynpickering.

Based on your feedback the remaining tasks for me are to:

- [x] round the floats to avoid error due to small numerical difference (e-5)
- [x] remove redundant dependencies from the notebook
- [x] move notebooks used for other publications

I intend to tag the master branch with `joss_review` tag after the entire review is over if that's ok.

**Comment by milicag** [comment]
@brynpickering I believe the issues are now addressed. Please test at your convenience.

**Comment by brynpickering** [comment]
Does the trick!

**Comment by milicag** [comment]
I'm glad. Please let me know if there is anything else you think belongs to this PR, otherwise I can merge it in.

**Comment by brynpickering** [comment]
You can merge this in if you like. I have some other general comments on the code to write up, but they can be addressed in another issue/PR combo.

**Comment by milicag** [comment]
Sounds good. Thank you!

**Pull request merged**
