### PR TITLE
Added contributing guidelines

### LINKED ISSUE #32: Missing contribution guidelines
The README does welcome contributions, but provides no framework doing so. [Contribution guidelines](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) would be a clear way to set expectations in terms of structure and content of contributions, and help to ensure the [community can grow](https://opensource.guide/building-community/). They don't need to be as in-depth as projects like Atom, but sufficient to avoid confusion between your expectations and potential contributions.

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)

### PR DESCRIPTION
**Pull request by milicag**
Closes #32.

### CODE REVIEW

**Comment by milicag** [comment]
@brynpickering @nmstreethran, this is ready for you to look at. Please let me know if you need any further edits.

**Comment by nmstreethran** [comment]
Thanks @milicag. I think the guidelines look great.

I think only the maintainers of the MSWH repository can create new branches directly. So, you can just state in step 4 that potential contributors have to fork the repository.

Could you add a link to the guidelines file in the README under 'Contributing'?

I think it would be good to add a sentence in the Sphinx documentation telling users that development primarily takes place on the GitHub repository, and that they can refer to the contributing guidelines and README for instructions on how to run tests. You could add this in `docs/source/models.rst` under the 'Usage' section, or alternatively create a new section.

**Comment by milicag** [comment]
@nmstreethran That makes a lot of sense. I also figured out the details on what "write" access means. I've learned so much in this process! Thank you thank you.

Based on your comment here and on the JOSS review issue I intend to:

- [x] Step 4 - use forks to contribute, not directly!
- [x] Move this to the final JOSS steps issue #16: In `models.rst` add a sentence in the Sphinx documentation telling users that development primarily takes place on the GitHub repository, and that they can refer to the contributing guidelines and README for instructions on how to run tests
- [x] Add a link to the guidelines file in the README under 'Contributing'
- [x] Add a short `statement of need` for future users in the README

**Comment by milicag** [comment]
@nmstreethran @brynpickering This is now addressed. Please let me know if you see that it needs any edits before I can merge.

**Pull request merged**
