### PR TITLE
Issue17 18 20 joss review

### LINKED ISSUE #17: Improve code readability
OK, the title makes it seem like the code isn't readable - I actually find it to be quite clear and clean! However, there are a few things that can be a bit jarring. Here I've split it into three sub-issues:

1. The code could do with generally being formatted to improve readability to be a bit more [PEP 8](https://www.python.org/dev/peps/pep-0008/)ish, e.g. the code column is very narrow and unnecessary backslashes turn up in quite a few places. The easiest approach to not have to think about manual formatting is to just use [Black](https://github.com/psf/black), which will reformat your code to PEP 8 standard with a one-liner. 

2. Something Black can't do is update variable names. In some instances these are a bit difficult to understand. There's no real reason to excessively shorten variable names in Python. A prime example is your lookup dictionaries for labels: `Converter.s`, `Converter.c`, and `Converter.r`; out of context they make no sense. Another example is `spec_hea_con` which is much easier to understand as `specific_heat_conductivity` (although perhaps this should be `thermal_conductivity`?). Full phrases, maybe with missing words are better than each word being shortened (i.e. `heat_conductivity` or `specific_heat` are both more informative than `spec_hea_con`, even if they're not perfectly "correct" descriptions in the thermodynamics community).

3. Finally, there's lots of repetition of filling dictionaries, which could either be simplified with helper functions or more `for` loops. As loops, e.g.
```python
self.params_piping[self.s['pipe_spec_hea_con']] =\
    params.loc[params[self.s['param']] == self.s['pipe_spec_hea_con'],
               self.s['param_value']].values[0]
self.params_piping[self.s['pipe_ins_thick']] = params.loc[
    params[self.s['param']] == self.s['pipe_ins_thick'],
    self.s['param_value']].values[0]
self.params_piping[self.s['dia_len_exp']] = params.loc[
    params[self.s['param']] == self.s['dia_len_exp'],
    self.s['param_value']].values[0]
```
could be 
```python
for i in ['pipe_spec_hea_con', 'pipe_ins_thick', 'dia_len_exp']:
    self.params_piping[self.s[i]] = params.loc[params[self.s['param']] == self.s[i], self.s['param_value']].values[0]
```
Since these repetitive code snippets are generally based on DataFrames, you could also just map the index to the long names and then transform the result into a dictionary:
```python
df.index = df.index.map(self.s)
self.params_piping = df.to_dict()
```

Note 1: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2695)
Note 2: from the perspective of the JOSS review, you can also stick with what you have, this is more of a side-note issue

### PR DESCRIPTION
**Pull request by milicag**
Closes #17, #18, #20.

### CODE REVIEW

**Comment by milicag** [comment]
@brynpickering, @nmstreethran:

I merged the previous PR, I opted to keep all installation instructions in the README, as I personally like to look at the detailed instructions on this repo's README, so I don't want to need to look further for it. Still, I did break it into simple and advanced sections that I think should make it easier for non-technical users, as well as for technical users.

This PR addresses further issues as listed in the PR description.

Please let me know if you have any questions. I ran the tests on a mac and on windows - tests run fine, and the web app too.

**Comment by milicag** [comment]
@brynpickering, @nmstreethran, as usual, I can address any requests you might have next weekend.

I took the liberty to look through review checklists, as I might take the role at some point, and I did not find any explicit request to have the installation instructions in a particular place on the repository. It just says: `Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.` I believe this is now addressed, though I am happy to add small fixes as you find needed.

If you see any further need for edits based on the review checklists, please let me know. I do intend to acknowledge your contributions through review and would love to make some parts of the code more sophisticated once I find time for it.

**Comment by nmstreethran** [comment]
Hi @milicag, thank you for the changes so far.

'Installation instructions' is a checklist item under the 'Documentation' heading. The [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation) also mentions that the README should include a "high-level overview" of the software documentation.

I still think that having only the simple conda instructions in README and moving the detailed instructions to the documentation, as suggested in https://github.com/LBNL-ETA/MSWH/issues/10#issuecomment-712304832, is more appropriate. The detailed instructions have steps for both conda and non-conda users, so there's no need to repeat the simple conda instructions in the documentation.

I also think that you should move steps 1 and 2 under 'Setup and Installation' to the detailed instructions, as the simple instructions already cover `pip` and `git-lfs`.

I will submit a new issue with my remaining comments later today, so you can have a look at them during the weekend.

**Comment by milicag** [comment]
> Hi @milicag, thank you for the changes so far.
> 
> 'Installation instructions' is a checklist item under the 'Documentation' heading. The [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation) also mentions that the README should include a "high-level overview" of the software documentation.
> 
> I still think that having only the simple conda instructions in README and moving the detailed instructions to the documentation, as suggested in [#10 (comment)](https://github.com/LBNL-ETA/MSWH/issues/10#issuecomment-712304832), is more appropriate. The detailed instructions have steps for both conda and non-conda users, so there's no need to repeat the simple conda instructions in the documentation.
> 
> I also think that you should move steps 1 and 2 under 'Setup and Installation' to the detailed instructions, as the simple instructions already cover `pip` and `git-lfs`.
> 
> I will submit a new issue with my remaining comments later today, so you can have a look at them during the weekend.

Looking forward to it!

**Comment by milicag** [comment]
> Hi @milicag, thank you for the changes so far.
> 
> 'Installation instructions' is a checklist item under the 'Documentation' heading. The [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation) also mentions that the README should include a "high-level overview" of the software documentation.
> 
> I still think that having only the simple conda instructions in README and moving the detailed instructions to the documentation, as suggested in [#10 (comment)](https://github.com/LBNL-ETA/MSWH/issues/10#issuecomment-712304832), is more appropriate. The detailed instructions have steps for both conda and non-conda users, so there's no need to repeat the simple conda instructions in the documentation.
> 
> I also think that you should move steps 1 and 2 under 'Setup and Installation' to the detailed instructions, as the simple instructions already cover `pip` and `git-lfs`.
> 
> I will submit a new issue with my remaining comments later today, so you can have a look at them during the weekend.

Looking forward to it!

**Comment by milicag** [comment]
@brynpickering Is this ready to merge?

**Comment by brynpickering** [comment]
I'm going to assume yes based on activity in the issues, but can't really check in detail. The first run of Black always throws up so many changes that pinpointing non-Black edits in the same commit is impossible. Anyway, I'm fine with it all being merged.

**Comment by milicag** [comment]
@brynpickering Black didn't want to format `models.py`. If there is anything that really stands our I can edit it or look further into that. I'll merge and let's do an another round!

**Comment by milicag** [comment]
One thing I don't like about current installation instructions is that conda gets mentioned and used before any mention on how to install it. If we are targeting non-technical audience, then this might be a wrong assumption, that they would already know about it.

**Comment by milicag** [comment]
tests ok

**Pull request merged**
